import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=dirname(fileURLToPath(import.meta.url));
const baseURL=process.env.HERO_URL || 'http://localhost:3000';
const browser=await chromium.launch({headless:true,channel:'chrome',args:['--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist']});
const failures=[];
async function screenshotCanvas(page,name){const data=await page.locator('[data-testid="hero-terrain"] canvas').evaluate(canvas=>canvas.toDataURL('image/png'));fs.writeFileSync(resolve(root,name),Buffer.from(data.split(',')[1],'base64'));return data;}
try{
  const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  page.on('pageerror',e=>failures.push(e.message));
  await page.goto(baseURL,{waitUntil:'domcontentloaded'});
  const figure=page.locator('[data-testid="hero-terrain"]');
  await figure.locator('canvas').waitFor();
  await page.waitForFunction(()=>document.querySelector('[data-testid="hero-terrain"]').dataset.phase==='mountain',{timeout:45000});
  await screenshotCanvas(page,'beshtau-mountain.png');
  await page.waitForTimeout(4000);
  await screenshotCanvas(page,'beshtau-transition.png');
  await page.waitForTimeout(1500);
  await screenshotCanvas(page,'beshtau-build.png');
  await page.waitForTimeout(1200);
  await screenshotCanvas(page,'beshtau-pullback.png');
  await page.waitForFunction(()=>document.querySelector('[data-testid="hero-terrain"]').dataset.phase==='ring',{timeout:20000});
  await page.waitForTimeout(250);
  const before=await screenshotCanvas(page,'beshtau-ring.png');
  await page.screenshot({path:resolve(root,'hero-desktop.png')});
  const bounds=await figure.locator('canvas').boundingBox();assert(bounds);
  await page.mouse.move(bounds.x+bounds.width*.5,bounds.y+bounds.height*.5);
  await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.76,bounds.y+bounds.height*.6,{steps:14});await page.mouse.up();
  await page.waitForTimeout(600);
  const rotated=await screenshotCanvas(page,'beshtau-rotated.png');assert.notEqual(rotated,before,'Mouse drag must rotate the actual 3D scene');
  await figure.locator('canvas').focus();await page.keyboard.press('ArrowLeft');await page.waitForTimeout(300);
  const keyboard=await screenshotCanvas(page,'beshtau-keyboard.png');assert.notEqual(keyboard,rotated,'Keyboard rotation must change the scene');
  const href=await figure.getByRole('link',{name:'Открыть в мастерской'}).getAttribute('href');
  const config=new URL(href,'http://localhost:3000');
  for(const [key,value]of Object.entries({lat:'44.09865',lng:'43.02519',r:'2179',b:'-90',h:'3.77',m:'silver',sf:'polished',sz:'17',d:'high'}))assert.equal(config.searchParams.get(key),value);
  await figure.getByRole('button',{name:'Повторить'}).click();
  await page.waitForFunction(()=>document.querySelector('[data-testid="hero-terrain"]').dataset.phase==='mountain');
  await figure.getByRole('button',{name:'Смотреть кольцо'}).click();
  assert.equal(await figure.getAttribute('data-phase'),'ring');
  console.log('PASS desktop: animation completes, drag, keyboard, replay, skip and exact configuration link');
  const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  mobile.on('pageerror',e=>failures.push(e.message));
  await mobile.goto(baseURL,{waitUntil:'domcontentloaded'});
  await mobile.locator('[data-testid="hero-terrain"]').scrollIntoViewIfNeeded();
  await mobile.waitForFunction(()=>document.querySelector('[data-testid="hero-terrain"]').dataset.phase==='ring',{timeout:30000});
  await mobile.screenshot({path:resolve(root,'hero-mobile.png')});
  const overflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,'No horizontal overflow on mobile');
  const mobileCanvas=mobile.locator('[data-testid="hero-terrain"] canvas');
  const touchBefore=await mobileCanvas.evaluate(canvas=>canvas.toDataURL());
  const touchBounds=await mobileCanvas.boundingBox();
  const cdp=await mobile.context().newCDPSession(mobile);
  const start={x:touchBounds.x+touchBounds.width*.45,y:touchBounds.y+touchBounds.height*.4};
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});
  for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+i*5,y:start.y+i*2}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await mobile.waitForTimeout(600);
  assert.notEqual(await mobileCanvas.evaluate(canvas=>canvas.toDataURL()),touchBefore,'Touch drag must rotate the scene');
  await mobile.locator('[data-testid="hero-terrain"] canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2');const ext=gl.getExtension('WEBGL_lose_context');ext.loseContext();});
  await mobile.waitForFunction(()=>document.querySelector('[data-testid="hero-terrain"]').dataset.phase==='error');
  assert.equal(await mobile.getByRole('button',{name:'Загрузить 3D'}).count(),1);
  await mobile.getByRole('button',{name:'Загрузить 3D'}).click();
  await mobile.waitForFunction(()=>document.querySelector('[data-testid="hero-terrain"]').dataset.phase==='ring',null,{timeout:30000});
  assert.equal(await mobile.locator('[data-testid="hero-terrain"] img').evaluate(img=>img.complete && img.naturalWidth>0),true,'Fallback poster must load');
  console.log('PASS mobile: responsive layout, touch rotation, WebGL fallback and retry');
  const reduced=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});
  reduced.on('pageerror',e=>failures.push(e.message));
  await reduced.goto(baseURL,{waitUntil:'domcontentloaded'});
  await reduced.waitForFunction(()=>document.querySelector('[data-testid="hero-terrain"]').dataset.phase==='ring',{timeout:30000});
  console.log('PASS reduced motion: starts with the interactive finished ring');
  assert.deepEqual(failures,[],'No browser runtime errors');
}finally{await browser.close();}
